### ISSUE TITLE
[Windows] Prefix/Squash commits

### ISSUE THREAD

**Issue by pentix** [pentix/qjournalctl#45]
Prefix/Squash all "fix CI" commits together to keep the commit history somewhat structured

**Comment by alacasta** [comment]
Hello @pentix 

I don't know how to deal with this considering that the commits are already pushed up. 

Can you please provide some hint on that?

**Comment by pentix** [comment]
If you allow I would squash some commits together (for example all CI trials) and add the `Windows:` prefix to your commits, prior to merging everything to the master branch. I'd do this only once the Windows Release is completed, and before merging everything, such that I don't mess up the git history right now 😅

**Comment by alacasta** [comment]
Yes, sounds not a problem ! 

Then, i assume you will handle them, right?

Apart from this... it was mainly for CI/CD using appveyor. Should we open an issue to effectivelly setup appveyor? I have mine ready, but i'd prefer to assciate to your account since you are the owner of the codebase. I can provide you some support when setting it up to avoid this "fix CI" commits btw :) In fact, it would be nice if we coul have automated the release process for both, linux and windows and also connect this with https://github.com/pentix/qjournalctl/issues/47 for a better versioning. If you agree
- We can open a ticket specifically for this
- You can manage on your own and we can keep discussing it via e-mail

**Comment by pentix** [comment]
Ahh I should have seen this a few minutes earlier, I just deleted some old configuration from AppVeyor (Apparently I tried this when I wanted to setup Travis) and reinstantiated the project.

Yes, I will handle the commits as soon as the everything else is ready :)

**Comment by pentix** [comment]
Hi @alacasta 

I went through all our commits and reworded/squashed some of them.
All commit messages start with the prefix `Windows:` to signalize when they were introduced. Also, at some occasions, commits introduced some code only for the next commit to slightly modify (`2017` -> `2019`, add a trailing slash, etc.) the code again.

I squashed some of these commits into one commit, such that the commit history shows significant changes while still showing the progress it took to get there. :relieved:

**Comment by alacasta** [comment]
> Hi @alacasta
> 
> I went through all our commits and reworded/squashed some of them.
> All commit messages start with the prefix `Windows:` to signalize when they were introduced. Also, at some occasions, commits introduced some code only for the next commit to slightly modify (`2017` -> `2019`, add a trailing slash, etc.) the code again.
> 
> I squashed some of these commits into one commit, such that the commit history shows significant changes while still showing the progress it took to get there. 😌

Thanks! I made many commits when tinkering around `appveyor`. Thanks for squashing them!
