### ISSUE TITLE
[Windows] Build script: Log actually executed commands

### ISSUE THREAD

**Issue by pentix** [pentix/qjournalctl#46]
https://github.com/pentix/qjournalctl/pull/41#discussion_r399588228

**Comment by alacasta** [comment]
Hi @pentix, 

I'd like to handle this issue. However, it is not clear to me. It was asked in #41 (comment): 
> What about adding call .....\.....\vcvarsall.bat x64 directly for the user? I guess the problem is we would need to find the correct installation path of Visual Studio, right? 😬

The answer is no. The problem is that it is not possible to call directly from the script to `call .....\.....\vcvarsall.bat` because it changes the context and the script does not keep running. therefore, has no effect. In turn, it is recommended to the user to run such script explicitelly to set up the terminal where tu run the `autogen_and_build.bat` script. 

So, Is then this issue just regarding to explicitelly show the commands while they are run in the script? Could you please provide a better description?

Thanks!

**Comment by pentix** [comment]
@alacasta The makeover of the script seems to work fine and should automatically determine whether the 2017 or 2019 version of Visual Studio should be used. 

The script is now pretty self-contained, i.e. it can be started using a double click in explorer and does not need to be invoked via a Visual Studio shell...
It works on AppVeyor as well as for me after setting the QtPath and the VCPKG path. I hope it works for you too? :)

**Comment by pentix** [comment]
Sorry, I guess I was not very clear and I misunderstood parts of the script before creating the issue, due to my bad batch skills. 

I tought the `REM` sections were remarks to be printed (à la `echo` / `printf`) and I only now understood you had them actually inside only as comments, such that the user can configure it's build...

I had to read up a lot on batch scripting but I think the current solution is a bit simpler to use and configure now, what do you think? Sorry for the misunderstanding! 😬

**Comment by alacasta** [comment]
> @alacasta The makeover of the script seems to work fine and should automatically determine whether the 2017 or 2019 version of Visual Studio should be used. 
> 
> 
> 
> The script is now pretty self-contained, i.e. it can be started using a double click in explorer and does not need to be invoked via a Visual Studio shell...

LGTM!! Now is quite clearer and supports both platforms in a more straightforward way! 👍

> It works on AppVeyor as well as for me after setting the QtPath and the VCPKG path. I hope it works for you too? :)

I will check! Nonetheless, please realize that in the `appveyor.yaml` file there is also one call to `Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat` that perhaps can be removed with the current solution. 😊

**Comment by pentix** [comment]
Thank you for pointing this out, the call has been removed and it seems to work fine :)

I'll close this issue as the problem seems solved to me. I might need to mention the changes again in the README, since I restructured your script, but I'll do this.
