### ISSUE TITLE
Installation instructions aren't quite complete.

### ISSUE THREAD

**Issue by speedbug78** [pentix/qjournalctl#63]
Built the code on a fresh install of LinuxCNC (Debian 9.0).

At this step: `sudo apt-get install qtbase5-dev cmake` I also needed to install openssl.
`cmake .. && sudo make install` would still never build due to an inability to find the proper path to openssl.  At this point I installed libssl-dev (sudo apt install libssl-dev) and that allowed libssh to build.

Run `./autogen.sh` didn't work and it's error message was cryptic (Project ERROR: libssh development package not found).  Turns out pkg-config was missing.

sudo apt install pkg-config

Now it builds, but doesn't run:
./qjournalctl: error while loading shared libraries: libssh.so.4: cannot open shared object file: No such file or directory

Copying libssh.so libssh.so.4 and libssh.so.4.8.4 into the same directory as qjournalctl didn't solve anything.

Copying libssh.so, libssh.so.4 and libssh.so.4.8.4 to /usr/lib/x86_64-linux-gnu/ finally solved this issue and now qjournalctl runs.  Yay.

**Comment by henrikp** [comment]
When building a package for Gentoo, I skipped the autogen.sh script completely and just ran qmake work it's magic in the root directory, no issues with finding anything nor compiling.

**Comment by pentix** [comment]
Hi @speedbug78

Thanks for reporting this! Sorry for my late answer, I found very little time to work on other projects in the last months and it seems I completely missed this issue. :grimacing: 

Indeed the build instructions differed from what I could test in the CI, due to different (old) versions of Qt and libssh
and you were the first one to notice.

I added `libssl-dev`, `pkg-config` as well as `zlib1g-dev` which seems to be required to build libssh later on.
Building it (still) works and I hope you saved someone else some trouble! I can't really reproduce and comprehend the missing .so error, maybe the libssh installation went wrong or this is a LinuxCNC-specific issue?

I'm happy you got it fixed and it works for you now, so thank you again for reporting :)

@henrikp And thank you for checking on this! Glad it works for you, too!
